### ISSUE TITLE
load failed

### ISSUE THREAD

**Issue by allanerox** [Xipooo/SOLIDPrinciplesDemo#1]
First things first, I'm new to this, please be patient.

I'm getting the following error when I try to load up the Solution project:
> [...]\SOLIDPrinciplesDemo.Solution.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  [...]\SOLIDPrinciplesDemo.Solution.csproj

If I add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the Project element, I get the following error:

> [...]\SOLIDPrinciplesDemo.Solution.csproj : error  : The attribute "Version" in element <PackageReference> is unrecognized.  [...]\SOLIDPrinciplesDemo.Solution.csproj

What have I failed to do?
Is further information required?

**Comment by Xipooo** [comment]
Make sure you have .NET Core 1.1 installed.  You can go to dot.net to get it.

**Comment by allanerox** [comment]
I tried that and it didn't work.
However I realised that it was being caused by using Studio 2015.
I've updated to 2017 and it works now.
Thanks.
